# CI de Nível 02 - Disparo Programado

# nome do nosso 'pipeline'
name: 'Execução Programada de Testes E2E'

# gatilho de execução manual
on:
  schedule:
    # cronograma de execução
    - cron: '0 6 * * 1' # executa toda segunda-feira às 06:00 hs

# trabalhos/tarefas dentro do pipeline
jobs:
  e2e-tests:
    # máquina que o job vai rodar
    runs-on: ubuntu-latest

    # passos do script
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências do projeto
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # execução dos testes E2E
      - name: Executando testes E2E
        run: yarn run e2e
