# CI de Nível 03 - Execução Automática em Push

name: 'Execução Automática - Push na main'

on:
  push:
    branches:
      - main # ou outro branch principal, como 'master' ou 'develop'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Executando testes E2E
        run: yarn run e2e
